project:
  type: website

website:
  title: "Rodrisam10.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
  comments:
  giscus:
    repo: Rodrisam10/Rodrisam10.github.io
    repo-id: R_kgDOMkhWNA
    category: Announcements
    category-id: DIC_kwDOMkhWNM4CjTuW
    mapping: pathname
    reactions-enabled: true
    theme: light
    lang: es
  theme: cosmo
  css: styles.css
  toc: true



