project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Y ahora qué"
        href: index.qmd
      - section: "R: lo que tienes que saber"
        contents:
          - basics-R.qmd
  title: "Rodrisam10.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    comments:
      giscus: 
        repo: quarto-dev/quarto-docs
    theme: lux
    css: styles.css
    toc: true



