project:
  type: website

website:
  title: "Rodrisam10.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
  comments:
  theme: cosmo
  css: styles.css
  toc: true



