project:
  type: website

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Y ahora qué"
        href: index.qmd
      - section: "Python: lo que tienes que saber"
        contents:
          - Python_y_yo.qmd
          - Python_essentials.qmd
      - section: "R: lo que tienes que saber"
        contents:
          - basics-R.qmd
  title: "Karlim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    comments:
      giscus: 
        repo: quarto-dev/quarto-docs
    theme: cosmo
    css: styles.css
    toc: true



